<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <PackageId>LilHermes</PackageId>
	  <Version>1.0.0</Version>
	  <Authors>Carlos-DV</Authors>
	  <Description>Wrapper ligero para RabbitMQ con soporte para .NET Standard 2.0</Description>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.4.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LilHermes.Abstractions\LilHermes.Abstractions.csproj" />
  </ItemGroup>

</Project>
